import { Inter } from 'next/font/google'
import { SurveyComponent } from '../components/Quiz';
import { useRouter } from 'next/router'; 

const inter = Inter({ subsets: ['latin'] })

const defaultJson = { 
maxTimeToFinish: 3600,
showTimerPanel: "bottom",
showProgressBar: "top",
progressBarType: "questions",
"title":"Yet another quiz about Flow blockchain","description":"Quiz generated by AI - 2023-07-17T22:24:00.422Z","logo":"https://qstn.open4glabs.xyz/android-chrome-192x192.png","pages":[{"name":"What is Flow blockchain primarily designed for?","title":"What is Flow blockchain primarily designed for?","elements":[{"name":"What is Flow blockchain primarily designed for?","title":"What is Flow blockchain primarily designed for?","type":"RADIOGROUP","points":3,"choices":[{"value":"Decentralized finance"},{"value":"Scalable games and digital collectibles"},{"value":"Supply chain management"},{"value":"Social media platforms"}],"isRequired":true,"correctAnswer":"Scalable games and digital collectibles"}]},{"name":"Which programming language is commonly used to develop smart contracts on the Flow blockchain?","title":"Which programming language is commonly used to develop smart contracts on the Flow blockchain?","elements":[{"name":"Which programming language is commonly used to develop smart contracts on the Flow blockchain?","title":"Which programming language is commonly used to develop smart contracts on the Flow blockchain?","type":"RADIOGROUP","points":2,"choices":[{"value":"Solidity"},{"value":"JavaScript"},{"value":"Python"},{"value":"Cadence"}],"isRequired":true,"correctAnswer":"Cadence"}]},{"name":"Which consensus algorithm does Flow blockchain utilize?","title":"Which consensus algorithm does Flow blockchain utilize?","elements":[{"name":"Which consensus algorithm does Flow blockchain utilize?","title":"Which consensus algorithm does Flow blockchain utilize?","type":"RADIOGROUP","points":2,"choices":[{"value":"Proof of Work (PoW)"},{"value":"Proof of Stake (PoS)"},{"value":"Delegated Proof of Stake (DPoS)"},{"value":"Proof of Authority (PoA)"}],"isRequired":true,"correctAnswer":"Delegated Proof of Stake (DPoS)"}]},{"name":"What is the native cryptocurrency of the Flow blockchain?","title":"What is the native cryptocurrency of the Flow blockchain?","elements":[{"name":"What is the native cryptocurrency of the Flow blockchain?","title":"What is the native cryptocurrency of the Flow blockchain?","type":"RADIOGROUP","points":1,"choices":[{"value":"Ether"},{"value":"Bitcoin"},{"value":"Flow token"},{"value":"Ripple"}],"isRequired":true,"correctAnswer":"Flow token"}]},{"name":"How does Flow blockchain aim to address scalability challenges?","title":"How does Flow blockchain aim to address scalability challenges?","elements":[{"name":"How does Flow blockchain aim to address scalability challenges?","title":"How does Flow blockchain aim to address scalability challenges?","type":"RADIOGROUP","points":3,"choices":[{"value":"Through sharding"},{"value":"Through off-chain transactions"},{"value":"Through sidechains"},{"value":"Through a resource-oriented programming model"}],"isRequired":true,"correctAnswer":"Through sharding"}]},{"name":"Who developed the Flow blockchain?","title":"Who developed the Flow blockchain?","elements":[{"name":"Who developed the Flow blockchain?","title":"Who developed the Flow blockchain?","type":"RADIOGROUP","points":2,"choices":[{"value":"Ethereum Foundation"},{"value":"Cardano Foundation"},{"value":"Dapper Labs"},{"value":"Ripple Labs"}],"isRequired":true,"correctAnswer":"Dapper Labs"}]},{"name":"What is the purpose of Flow's resource-oriented programming model?","title":"What is the purpose of Flow's resource-oriented programming model?","elements":[{"name":"What is the purpose of Flow's resource-oriented programming model?","title":"What is the purpose of Flow's resource-oriented programming model?","type":"RADIOGROUP","points":2,"choices":[{"value":"To increase transaction speed"},{"value":"To enhance security measures"},{"value":"To simplify smart contract development"},{"value":"To enable cross-chain interoperability"}],"isRequired":true,"correctAnswer":"To simplify smart contract development"}]},{"name":"Which major project utilized the Flow blockchain for its initial NFT launch?","title":"Which major project utilized the Flow blockchain for its initial NFT launch?","elements":[{"name":"Which major project utilized the Flow blockchain for its initial NFT launch?","title":"Which major project utilized the Flow blockchain for its initial NFT launch?","type":"RADIOGROUP","points":3,"choices":[{"value":"CryptoKitties"},{"value":"Decentraland"},{"value":"Axie Infinity"},{"value":"NBA Top Shot"}],"isRequired":true,"correctAnswer":"NBA Top Shot"}]},{"name":"What is the maximum supply of Flow tokens?","title":"What is the maximum supply of Flow tokens?","elements":[{"name":"What is the maximum supply of Flow tokens?","title":"What is the maximum supply of Flow tokens?","type":"RADIOGROUP","points":1,"choices":[{"value":"10 million"},{"value":"100 million"},{"value":"1 billion"},{"value":"10 billion"}],"isRequired":true,"correctAnswer":"10 billion"}]},{"name":"How does Flow blockchain handle transaction fees?","title":"How does Flow blockchain handle transaction fees?","elements":[{"name":"How does Flow blockchain handle transaction fees?","title":"How does Flow blockchain handle transaction fees?","type":"RADIOGROUP","points":2,"choices":[{"value":"Through a fixed gas price"},{"value":"Through a dynamic fee market"},{"value":"Through a proof-of-stake mechanism"},{"value":"Through a subscription-based model"}],"isRequired":true,"correctAnswer":"Through a dynamic fee market"}]}]};

export default function Quiz() {
  const router = useRouter();

  const onComplete = (surveyModel: any) => {
    console.log(surveyModel);
    setTimeout(() => router.push('/reward'), 2000);
    return;
  }

    return (
      <main
        className={`${inter.className}`}
      >
<div className="relative flex sm:min-h-screen min-h-full flex-col justify-center overflow-hidden bg-gray-50 sm:py-12">
  <img src="/img/beams.jpg" alt="" className="absolute top-1/2 left-1/2 max-w-none -translate-x-1/2 -translate-y-1/2" width="1308" />
  <div className="absolute inset-0 bg-[url(/img/grid.svg)] bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
  <div className="relative sm:bg-white sm:pt-5 sm:pb-4 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-lg sm:rounded-lg sm:px-10">
    <div className="mx-auto max-w-full">
    <div className="flex flex-col p-3 mt-48">

      <SurveyComponent surveyJson={defaultJson} onComplete={onComplete} />
    </div>
</div>
</div>
</div>
    </main>

    )
}